name = "search-engine"
main = "src/main.py"
compatibility_date = "2026-07-19"
compatibility_flags = [ "python_workers" ]

[[d1_databases]]
binding = "DB"
database_name = "search-index-db"
database_id = "6ff2c7b4-ea07-42a4-8c5d-7f3dac79dea8"
